name: Deploy to Vercel

on: [workflow_dispatch]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.2.2

      - name: Install Dependencies
        run: pnpm i

      - name: Check Code Problems
        run: pnpm lint:check

      - name: Vercel Deployment
        uses: amondnet/vercel-action@v20
        with:
          vercel-args: '--prod'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
