name: TypeCheck and Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 18

      - name: Install Dependencies
        run: pnpm install

      - name: Run contentlayer build
        run: pnpm contentlayer build

      - name: Type Checking
        run: pnpm typecheck

      - name: Lint Project
        run: pnpm lint
